"""empty message

Revision ID: 407833c9c1cb
Revises: None
Create Date: 2014-05-20 22:39:57.864655

"""

# revision identifiers, used by Alembic.
revision = '407833c9c1cb'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('role', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nickname')
    )
    op.create_table('graphs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('graph_name', sa.String(length=240), nullable=True),
    sa.Column('keyword_1', sa.String(length=240), nullable=True),
    sa.Column('keyword_2', sa.String(length=240), nullable=True),
    sa.Column('date_low', sa.String(length=10), nullable=True),
    sa.Column('date_high', sa.String(length=10), nullable=True),
    sa.Column('granularity', sa.String(length=5), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('graphs')
    op.drop_table('users')
    ### end Alembic commands ###
